DECLARE @REPORTDATE DATE;

SET @REPORTDATE = '2016-11-18';

INSERT INTO custom.Instruction_Blended_Fact_v2 (PLATFORMKEY,STUDENTKEY,SCHOOLKEY,DATE,SUBJECT,PROGRESS1,PROGRESS2,MASTERY,USAGE,ALERTS,HAS_ALERTS,MATERIAL_GRADELEVEL)
SELECT
1 AS PLATFORMKEY
,DSTU.STUDENTKEY
,SCHOOLKEY
,REPORTDATE
,0 AS SUBJECT
,K_5_PROGRESS AS PROGRESS
,(SELECT 
	SUM(CAST(MINUTES_LOGGED_LAST_WEEK AS INT)) 
	FROM [CUSTOM].[INSTRUCTION_STMATH_LJ] ST_USAGE_SUB 
	WHERE DSTU.SYSTEMSTUDENTID=ST_USAGE_SUB.SCHOOL_STUDENT_ID AND ST_USAGE_SUB.REPORTDATE<=@REPORTDATE AND ST_USAGE_SUB.START_YEAR=ST.START_YEAR) AS PROGRESS2 --USAGE YTD FOR USE IN EFFICIENCY CALCULATION (PROGRESS1/USAGE/60 -- %PROGRESS/HR)
,K_5_MASTERY AS MASTERY
,MINUTES_LOGGED_LAST_WEEK AS USAGE
,NULL AS ALERTS
,CASE 
	WHEN CUR_HURDLE_NUM_TRIES>9 THEN 1 
	ELSE 0 
 END AS HAS_ALERTS
,CASE 
	WHEN GCD LIKE 'First%' then 1
	WHEN GCD LIKE 'Second%' then 2
	WHEN GCD LIKE 'Third%' then 3
	WHEN GCD LIKE 'Fourth%' then 4
	WHEN GCD LIKE 'Fifth%' then 5
	WHEN GCD LIKE 'Sixth%' then 6
	WHEN GCD LIKE 'Seventh%' then 7
	WHEN GCD LIKE 'Eighth%' then 8
	ELSE Null
 END MATERIAL_GRADELEVEL
FROM [CUSTOM].[INSTRUCTION_STMATH_LJ] ST
JOIN [DW].[DW_DIMSTUDENT] DSTU ON DSTU.SYSTEMSTUDENTID=ST.SCHOOL_STUDENT_ID
JOIN [CUSTOM].[CUSTOM_STUDENTBRIDGE] B ON B.SYSTEMSTUDENTID=DSTU.SYSTEMSTUDENTID
JOIN [POWERSCHOOL].[POWERSCHOOL_STUDENTS] S ON S.STUDENT_NUMBER=B.STUDENT_NUMBER
JOIN [DW].[DW_DIMSCHOOL] DSCH ON DSCH.SYSTEMSCHOOLID=S.SCHOOLID
WHERE DSCH.SYSTEMSCHOOLID!='-----'
AND REPORTDATE=@REPORTDATE--'${ReportDate}';
