
DROP TABLE INSTRUCTION_BLENDED_PLATFORM_PROGRESS
CREATE TABLE INSTRUCTION_BLENDED_PLATFORM_PROGRESS
(ID INT IDENTITY(1,1) PRIMARY KEY
,SCHOOLID VARCHAR(20) NOT NULL
,REPORTDATE DATE NOT NULL
,INSESSION INT NOT NULL
,DAYSINWEEK INT NOT NULL
,PLATFORMKEY INT NOT NULL
,TOTALDAYS INT NOT NULL
,DAYSTODATE INT NOT NULL)

CREATE INDEX PLATFORM_PROGRESS_INDEX ON CUSTOM.INSTRUCTION_BLENDED_PLATFORM_PROGRESS(SCHOOLID,REPORTDATE,PLATFORMKEY)

INSERT INTO CUSTOM.INSTRUCTION_BLENDED_PLATFORM_PROGRESS (SCHOOLID, REPORTDATE, INSESSION, DAYSINWEEK, PLATFORMKEY, TOTALDAYS, DAYSTODATE)
SELECT 
 A.SCHOOLID,
 A.FULLDATE,
 A.INSESSION,
 A.DAYS,
 A.PLATFORMKEY,
 A.TOTALDAYS
,(SELECT SUM(CAST(B.INSESSION AS INT)) 
		 FROM 
		 (SELECT 
	     U.SCHOOLID
		,FULLDATE
		,C.INSESSION
		,SUM(CAST(INSESSION AS INT)) DAYS
		,PLATFORMKEY
		,SUB2.TOTALDAYS
		,C.SCHOOLYEAR
		FROM [dw].[DW_dimSchoolCalendar] C
		JOIN INSTRUCTION_BLENDED_PLATFORM_USAGE_DATES U
			ON C.SYSTEMSCHOOLID=U.SCHOOLID
			AND C.FULLDATE BETWEEN U.FIRSTDAY AND U.LASTDAY
		JOIN (SELECT --Returns table of total days by school and school year
				SCHOOLID
			,SUM(CAST(INSESSION AS INT)) TOTALDAYS
			,C.SCHOOLYEAR
			FROM [DW].[DW_DIMSCHOOLCALENDAR] C
			JOIN INSTRUCTION_BLENDED_PLATFORM_USAGE_DATES U
				ON C.SYSTEMSCHOOLID=U.SCHOOLID
				AND C.FULLDATE BETWEEN U.FIRSTDAY AND U.LASTDAY
			GROUP BY 
				SCHOOLID
				,PLATFORMKEY
				,U.FIRSTDAY
				,U.LASTDAY
				,C.SCHOOLYEAR) SUB2 ON SUB2.SCHOOLID=U.SCHOOLID AND SUB2.SCHOOLYEAR=C.SCHOOLYEAR
		GROUP BY U.SCHOOLID,FULLDATE,INSESSION,PLATFORMKEY,SUB2.TOTALDAYS,C.SCHOOLYEAR) B 
		WHERE B.FULLDATE<=A.FULLDATE AND B.SCHOOLID=A.SCHOOLID AND B.PLATFORMKEY=A.PLATFORMKEY AND B.SCHOOLYEAR = A.SCHOOLYEAR) DAYSTODATE
FROM (SELECT 
		 U.SCHOOLID
		,FULLDATE
		,C.INSESSION
		,SUM(CAST(INSESSION AS INT)) DAYS
		,PLATFORMKEY
		,SUB2.TOTALDAYS
		,C.SCHOOLYEAR
		FROM [dw].[DW_dimSchoolCalendar] C
		JOIN INSTRUCTION_BLENDED_PLATFORM_USAGE_DATES U
			ON C.SYSTEMSCHOOLID=U.SCHOOLID
			AND C.FULLDATE BETWEEN U.FIRSTDAY AND U.LASTDAY
				JOIN (SELECT 
					 SCHOOLID
					,SUM(CAST(INSESSION AS INT)) TOTALDAYS
					,C.SCHOOLYEAR
					FROM [DW].[DW_DIMSCHOOLCALENDAR] C
					JOIN INSTRUCTION_BLENDED_PLATFORM_USAGE_DATES U
						ON C.SYSTEMSCHOOLID=U.SCHOOLID
						AND C.FULLDATE BETWEEN U.FIRSTDAY AND U.LASTDAY
					GROUP BY 
						SCHOOLID
						,PLATFORMKEY
						,U.FIRSTDAY
						,U.LASTDAY
						,C.SCHOOLYEAR) SUB2 ON SUB2.SCHOOLID=U.SCHOOLID AND SUB2.SCHOOLYEAR=C.SCHOOLYEAR
				GROUP BY U.SCHOOLID,FULLDATE,INSESSION,PLATFORMKEY,SUB2.TOTALDAYS,C.SCHOOLYEAR) A
