DECLARE @REPORTDATE DATE;

SET @REPORTDATE = '2016-12-02';

WITH ST_MEDIAN_MINUTES (STUID,MINS,REPORTDATE,ROWNUM,COUNTWEEKS) AS --THIS SECTION CREATES A TEMP TABLE WITH USAGE VALUES FOR EACH STUDENT
(
	SELECT 
	SCHOOL_STUDENT_ID,
	CAST(MINUTES_LOGGED_LAST_WEEK AS float),
	REPORTDATE,
	ROW_NUMBER() OVER (PARTITION BY SCHOOL_STUDENT_ID ORDER BY CAST(MINUTES_LOGGED_LAST_WEEK AS float)),
	COUNT(REPORTDATE) OVER (PARTITION BY SCHOOL_STUDENT_ID)
	FROM [CUSTOM].[INSTRUCTION_STMATH_LJ]
	WHERE REPORTDATE between '2016-08-01' and @REPORTDATE
	AND MINUTES_LOGGED_LAST_WEEK IS NOT NULL
)


INSERT INTO custom.Instruction_Blended_Fact_v2 (PLATFORMKEY,STUDENTKEY,SCHOOLKEY,DATE,SUBJECT,PROGRESS1,PROGRESS2,MASTERY,USAGE,USAGE_MEDIAN,USAGE_OUTLIER,ALERTS,HAS_ALERTS,MATERIAL_GRADELEVEL,TEACHER_NAME)
SELECT
1 AS PLATFORMKEY
,DSTU.STUDENTKEY
,SCHOOLKEY
,REPORTDATE
,0 AS SUBJECT
,K_5_PROGRESS AS PROGRESS --% PROGRESS YTD
,(SELECT 
	SUM(CAST(MINUTES_LOGGED_LAST_WEEK AS INT)) 
	FROM [CUSTOM].[INSTRUCTION_STMATH_LJ] ST_USAGE_SUB 
	WHERE DSTU.SYSTEMSTUDENTID=ST_USAGE_SUB.SCHOOL_STUDENT_ID AND ST_USAGE_SUB.REPORTDATE<=@REPORTDATE AND ST_USAGE_SUB.START_YEAR=ST.START_YEAR) AS PROGRESS2 --USAGE YTD FOR USE IN EFFICIENCY CALCULATION (PROGRESS1/(USAGE/30))
,K_5_MASTERY AS MASTERY
,COALESCE(MINUTES_LOGGED_LAST_WEEK,0) AS USAGE
,(SELECT -- THIS SUBQUERY USES THE TEMP TABLE TO CALCULATE THE MEDIAN, BASED ON TUTORIAL FOUND HERE: http://blogs.lessthandot.com/index.php/datamgmt/dbprogramming/it-s-hard-to-be/
	AVG(MINS)
	FROM ST_MEDIAN_MINUTES
	WHERE ROWNUM BETWEEN (COUNTWEEKS+1)/2 AND (COUNTWEEKS+2)/2
	AND STUID = DSTU.SYSTEMSTUDENTID
	GROUP BY STUID) USAGE_MEDIAN
,CASE WHEN MINUTES_LOGGED_LAST_WEEK>300 THEN 1 ELSE 0 END USAGE_OUTLIER
,NULL AS ALERTS
,CASE 
	WHEN CUR_HURDLE_NUM_TRIES>9 THEN 1 
	ELSE 0 
 END AS HAS_ALERTS
,CASE 
	WHEN GCD LIKE 'First%' then 1
	WHEN GCD LIKE 'Second%' then 2
	WHEN GCD LIKE 'Third%' then 3
	WHEN GCD LIKE 'Fourth%' then 4
	WHEN GCD LIKE 'Fifth%' then 5
	WHEN GCD LIKE 'Sixth%' then 6
	WHEN GCD LIKE 'Seventh%' then 7
	WHEN GCD LIKE 'Eighth%' then 8
	ELSE Null
 END MATERIAL_GRADELEVEL,
ST.TEACHER_NAME 
FROM [CUSTOM].[INSTRUCTION_STMATH_LJ] ST
JOIN [DW].[DW_DIMSTUDENT] DSTU ON DSTU.SYSTEMSTUDENTID=ST.SCHOOL_STUDENT_ID
JOIN [CUSTOM].[CUSTOM_STUDENTBRIDGE] B ON B.SYSTEMSTUDENTID=DSTU.SYSTEMSTUDENTID
JOIN [POWERSCHOOL].[POWERSCHOOL_STUDENTS] S ON S.STUDENT_NUMBER=B.STUDENT_NUMBER
JOIN [DW].[DW_DIMSCHOOL] DSCH ON DSCH.SYSTEMSCHOOLID=S.SCHOOLID
WHERE DSCH.SYSTEMSCHOOLID!='-----'
AND REPORTDATE = @REPORTDATE
